version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-ecoeclesia
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecoeclesia
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
    networks:
      - ecoeclesia-network

  postgres:
    image: postgres:16
    container_name: postgres-ecoeclesia
    restart: always
    environment:
      POSTGRES_DB: ecoeclesia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecoeclesia-network

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express-ecoeclesia
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - ecoeclesia-network

networks:
  ecoeclesia-network:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
