spring.application.name=EcoEcclesia

# MongoDB
spring.data.mongodb.uri=mongodb://root:root@localhost:27017/ecoeclesia?authSource=admin

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecoeclesia
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
security.jwt.secret=akdBczl2QWxpc0VhZGxBbm90aGVyU2VjdXJlU3RyaW5nMTIzNDU2Nzg5MA==
security.jwt.access-token-validity=15m
security.jwt.refresh-token-validity=168h

