spring.application.name=EcoEcclesia

# MongoDB
spring.data.mongodb.uri=mongodb://root:root@localhost:27017/ecoeclesia?authSource=admin

# JWT
security.jwt.secret=akdBczl2QWxpc0VhZGxBbm90aGVyU2VjdXJlU3RyaW5nMTIzNDU2Nzg5MA==
security.jwt.access-token-validity=15m
security.jwt.refresh-token-validity=168h

